// GmailWidgetTest.js
(function($){
Type.registerNamespace('GmailWidgetTest');GmailWidgetTest.Index=function(){}
GmailWidgetTest.Index.$4=function(){if(GmailWidgetTest.Index.$1!=null){if(GmailWidgetTest.Index.$2!==-1){var $0=Date.get_now().getDate();if($0>(GmailWidgetTest.Index.$2+60000)){GmailWidgetTest.Index.$14();}}}}
GmailWidgetTest.Index.$5=function(){GmailWidgetTest.Index.$11();if(!GmailWidgetTest.Index.$7()){if(!GmailWidgetTest.Index.$6()){if(chameleon.connected()){GmailWidgetTest.Index.$8();chameleon.initialize();}else{GmailWidgetTest.Index.$A();chameleon.initialize();}}}}
GmailWidgetTest.Index.$6=function(){var $0=false;var $1=chameleon.getSharedData();if($1==null){$1={};}if($1.accounts==null){$1.accounts=[];}var $2=null;if(($1.accounts).length>0){$2=($1.accounts)[0];if(GmailWidgetTest.Index.$1==null||$2.secret!==GmailWidgetTest.Index.$1.secret){GmailWidgetTest.Index.$1=$2;GmailWidgetTest.Index.$14();}$0=true;}return $0;}
GmailWidgetTest.Index.$7=function(){var $0=false;var $1=chameleon.getSharedData();if($1!=null&&$1.account_to_load!=null){var $2=chameleon.getSharedData();if($2==null){$2={};}if($2.accounts==null){$2.accounts=[];}var $3=null;for(var $4=0;$4<($2.accounts).length;$4++){if(($2.accounts)[$4].email===$1.account_to_load){$3=($2.accounts)[$4];$0=true;break;}}if($3!=null&&(GmailWidgetTest.Index.$1==null||$3.secret!==GmailWidgetTest.Index.$1.secret)){GmailWidgetTest.Index.$1=$3;GmailWidgetTest.Index.$14();}}return $0;}
GmailWidgetTest.Index.$8=function(){var $0={};$0.title='Register Your Account';chameleon.invalidate();if(chameleon.isInLayoutMode()){$0.caption='Tap the gear in the top right to register your Gmail Account and display unread messages from your inbox in this widget.';$0.noicon=true;GmailWidgetTest.Index.$3.chameleonWidgetConfigureHTML($0);GmailWidgetTest.Index.$3.chameleonInvalidate();}else{$0.caption='Tap here to register your Gmail Account and display unread messages from your inbox in this widget.';GmailWidgetTest.Index.$3.chameleonWidgetConfigureHTML($0);GmailWidgetTest.Index.$3.chameleonInvalidate();}}
GmailWidgetTest.Index.$9=function(){chameleon.invalidate();var $0={};$0.icon='images/inbox_ninja.png';$0.title='No un-read email';$0.caption="Guess you're an inbox ninja.";GmailWidgetTest.Index.$3.chameleonWidgetMessageHTML($0);GmailWidgetTest.Index.$3.chameleonInvalidate();}
GmailWidgetTest.Index.$A=function(){chameleon.invalidate();GmailWidgetTest.Index.$3.chameleonWidgetNeedWiFiHTML();GmailWidgetTest.Index.$3.chameleonInvalidate();}
GmailWidgetTest.Index.$B=function($p0){GmailWidgetTest.Index.$3.html($p0);}
GmailWidgetTest.Index.$C=function(){GmailWidgetTest.Index.$3.html('');}
GmailWidgetTest.Index.$D=function($p0){if($p0!=null){$p0.preventDefault();}var $0={};$0.url='settings.html';$0.result=function($p1_0,$p1_1){
if($p1_0){GmailWidgetTest.Index.$5();}};chameleon.promptHTML($0);}
GmailWidgetTest.Index.$E=function($p0){var $0='';if($p0!=null&&$p0.length>0){var $enum1=ss.IEnumerator.getEnumerator($p0);while($enum1.moveNext()){var $1=$enum1.current;$0+=GmailWidgetTest.Index.$F($1);}}GmailWidgetTest.Index.$3.html($0);chameleon.invalidate();GmailWidgetTest.Index.$3.chameleonInvalidate();GmailWidgetTest.Index.$12();chameleon.initialize();}
GmailWidgetTest.Index.$F=function($p0){var $0='';var $1=chameleon.get_chameleonInstance().timesince($p0.created);$0+="<div class='email-listing' id='"+$p0.id+"'>";$0+="<img src='images/gmail_unread_email.png' class='unread-email-icon' />";if($p0.url!=null){$0+="<a href='"+$p0.url+"' class='email-listing-title-link'>";}$0+="<p class='email-listing-title'>"+$p0.title+'</p>';if($p0.url!=null){$0+='</a>';}$0+="<p class='email-listing-from'>"+$p0.author_email+'</p>';$0+="<p class='email-listing-created'>"+$1+'</p>';$0+="<p class='email-listing-summary'>"+$p0.summary+'</p>';$0+='</div>';return $0;}
GmailWidgetTest.Index.$10=function(){var $0={};$0.id='feed_refresh';$0.action='start';$0.interval=GmailWidgetTest.Index.$0;$0.callback=GmailWidgetTest.Index.$14;chameleon.get_chameleonInstance().poll($0);}
GmailWidgetTest.Index.$11=function(){var $0={id:'feed_refresh',action:'stop'};chameleon.get_chameleonInstance().poll($0);}
GmailWidgetTest.Index.$12=function(){$('.email-listing-title-link').die('click',GmailWidgetTest.Index.$13).live('click',GmailWidgetTest.Index.$13);}
GmailWidgetTest.Index.$13=function($p0){if($p0!=null){$p0.preventDefault();}var $0='';if($p0!=null&&$p0.currentTarget!=null){$0=$p0.currentTarget.toString();}var $1={};$1.package='com.google.android.gm';$1.name='com.google.android.gm.ConversationListActivityGmail';if(chameleon.componentExists($1)||($0==null||!$0)){var $2={};$2.component=$1;$2.action='android.intent.action.MAIN';chameleon.intent($2);}else{var $3={};$3.action='android.intent.action.VIEW';$3.data=$0;chameleon.intent($3);}}
GmailWidgetTest.Index.$14=function(){if(GmailWidgetTest.Index.$1!=null){var $0=chameleon.getData();if($0==null){$0={};}var $1={};$1.text='UNREAD MESSAGES: '+(GmailWidgetTest.Index.$1.email).toUpperCase();chameleon.setTitle($1);if(chameleon.connected()){GmailWidgetTest.Index.$2=Date.get_now().getDate();var $2={};$2['token']=GmailWidgetTest.Index.$1.token;$2['secret']=GmailWidgetTest.Index.$1.secret;var $3={};$3.showloader=true;chameleon.showLoading($3);var $4={};$4.url='services/getmail.php';$4.data=JSON.stringify($2);$4.dataType='xml';$4.timeout=5000;$4.success=function($p1_0,$p1_1,$p1_2){
$3.showloader=false;chameleon.showLoading($3);GmailWidgetTest.Index.$C();var $1_0=[];var $1_1=$($p1_0);$1_1.find('feed > entry').each(function($p2_0,$p2_1){
var $2_0={};$2_0.id=$(this).find('id').text();$2_0.title=$(this).find('title').text();$2_0.author_email=$(this).find('author > email').text();$2_0.url=$(this).find('url').text();$2_0.created=$(this).find('issued').text();$2_0.summary=$(this).find('summary').text();$1_0.add($2_0);});if($1_0.length>0){GmailWidgetTest.Index.$E($1_0);chameleon.saveLocalData('cached_messages',$1_0);}else{GmailWidgetTest.Index.$C();GmailWidgetTest.Index.$9();chameleon.initialize();}GmailWidgetTest.Index.$10();};$4.error=function($p1_0,$p1_1,$p1_2){
$3.showloader=false;chameleon.showLoading($3);GmailWidgetTest.Index.$10();};$.ajax($4);}else{var $5=chameleon.getLocalData('cached_messages');if($5!=null){GmailWidgetTest.Index.$E($5);}else{GmailWidgetTest.Index.$A();}}}else{GmailWidgetTest.Index.$11();}}
GmailWidgetTest.Index.registerClass('GmailWidgetTest.Index');GmailWidgetTest.Index.$0=60000*5;GmailWidgetTest.Index.$1=null;GmailWidgetTest.Index.$2=-1;GmailWidgetTest.Index.$3=null;(function(){$(function(){
GmailWidgetTest.Index.$3=$('#chameleon-widget');var $1_0={};$1_0.onLoad=function(){
GmailWidgetTest.Index.$5();};$1_0.onScrollTop=function(){
if(GmailWidgetTest.Index.$1!=null&&chameleon.connected()){GmailWidgetTest.Index.$4();GmailWidgetTest.Index.$10();}};$1_0.onScrollElsewhere=function(){
GmailWidgetTest.Index.$11();};$1_0.onLayoutModeStart=function(){
if(GmailWidgetTest.Index.$1!=null){GmailWidgetTest.Index.$11();}else{if(chameleon.connected()){GmailWidgetTest.Index.$8();}else{GmailWidgetTest.Index.$A();}}};$1_0.onLayoutModeComplete=function(){
if(GmailWidgetTest.Index.$1!=null){GmailWidgetTest.Index.$10();GmailWidgetTest.Index.$4();}else{if(chameleon.connected()){GmailWidgetTest.Index.$8();}else{GmailWidgetTest.Index.$A();}}};$1_0.onConnectionAvailableChanged=function($p2_0){
if($p2_0){if(GmailWidgetTest.Index.$1!=null){GmailWidgetTest.Index.$14();}else{GmailWidgetTest.Index.$5();}}else{GmailWidgetTest.Index.$11();if(GmailWidgetTest.Index.$1==null){GmailWidgetTest.Index.$A();}}};$1_0.onConfigure=function(){
GmailWidgetTest.Index.$11();GmailWidgetTest.Index.$D(null);};$1_0.onTitleBar=function(){
GmailWidgetTest.Index.$13(null);};$1_0.onRefresh=function(){
if(GmailWidgetTest.Index.$1!=null){GmailWidgetTest.Index.$14();}};chameleon.widget($1_0);});})();
})(jQuery);// This script was generated using Script# v0.7.4.0
